### PR TITLE
Add Issue Templates

### PR DESCRIPTION
**Pull request by Shluffy**
This adds issue templates. Test them at my fork.

Please only merge when all reviews approve.

### CODE REVIEW

**Comment by ZI-Youtuber** [comment]
@Shluffy Where did you find them from?

**Comment by ZI-Youtuber** [comment]
@Shluffy Also add me as a assignne for each issue template pls

**Comment by ZI-Youtuber** [comment]
@Shluffy For some reason while i was testing it it only was assignning me not you

**Comment by ZI-Youtuber** [comment]
@Shluffy When going to your area it only assigned you

**Comment by Shluffy** [comment]
> @Shluffy For some reason while i was testing it it only was assignning me not you

yes, as I am the main dev on this, so it is my problem to fix bugs. however, I will add you to feature requests though.

**Comment by Shluffy** [comment]
@ZI-Youtuber  now assigns both of us, so should work fine.

**Pull request merged**
