### PR TITLE
Make this for console

### LINKED ISSUE #8: Recent Changes and new changes
All the changes, redirecttoscratchproject.js was pretty much copy and paste, and I had to make some changes that should have been done in the first place (https://github.com/Scratch-Dev-Team/Scratch-ConsoleBased-Extensions/commit/36a503fd03be867b2536ba76e6fc5abe7273cd58#diff-3c445e62ae8dba31393b8060f3ccb62724ccf595162090b6d64d42465595e285)
I would also like to have admin, and be the only admin of this repo. 
And what happened to the title?

- [ ] Change back title/Make it work for both (adding on console may not work because of one of the bookmarklet code elements)

### PR DESCRIPTION
**Pull request by Shluffy**
Resolves #8

### CODE REVIEW

**Comment by ZI-Youtuber** [comment]
wait what?

**Comment by ZI-Youtuber** [comment]
can you explain more?

**Comment by Shluffy** [comment]
Not ready to review, still more for me to do

**Comment by Shluffy** [comment]
> can you explain more?

the `javascript;` may make it not work, as well as making it have instructions for bookmarklet **and console**

**Review by ZI-Youtuber — APPROVED** [review]

**Comment by Shluffy** [comment]
I would like a review from @xItzDiamondx as he is part of this repo and has helped with this

**Comment by Shluffy** [comment]
I resolved the conflicts, so now merging as approved

**Pull request merged**
